# Generated by Django 4.2.30 on 2026-08-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descripcion_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre_es',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
