# Generated by Django 4.2.30 on 2026-08-22 23:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion_es',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
